yt-dlp -f 18 https://drive.google.com/file/d/1hPxx1iiMaGQgqIp-ySV_8-Vp5fgcNbnO/view 
yt-dlp -f 18 https://drive.google.com/file/d/1BrZdRDOwAFCz2Buf5EGxhOfhvS5uqpdm/view 
yt-dlp -f 18 https://drive.google.com/file/d/1pKcFILKiFRa8FMxZ0w3LyQav4QBFtKYO/view 
yt-dlp -f 18 https://drive.google.com/file/d/1595oLw9jc3piOsQvpF-csv3GuwtcXObQ/view 
yt-dlp -f 18 https://drive.google.com/file/d/1GK88eu9Qv-bypt1Oo0RHOS70t3CMQ1xS/view 
yt-dlp -f 18 https://drive.google.com/file/d/1WGX07ggmaYeVWGPRtKkDD5AhJhquDYXM/view 
yt-dlp -f 18 https://drive.google.com/file/d/1HST1l1cc0yOZKTrj8K_7s9Dy63C5P50B/view 
yt-dlp -f 18 https://drive.google.com/file/d/1dytEAGBZpFqTs9ROxnqOxiLb8u-Vj0J2/view 
yt-dlp -f 18 https://drive.google.com/file/d/14Nmno5fUn9Glkg2E3mo7qlEf9w5_W0aW/view 
yt-dlp -f 18 https://drive.google.com/file/d/135qfMZqd1BPrItfpMyg5Tsokv4E6yXwt/view 
yt-dlp -f 18 https://drive.google.com/file/d/1V2yiMJ1Ljw6LvXOAapIycQ0zXvmuLTnI/view 
yt-dlp -f 18 https://drive.google.com/file/d/11JtXW922L4pAS-ts0gyZ1_qSBEqJfzQa/view 
yt-dlp -f 18 https://drive.google.com/file/d/1rTbqgaBDjUbsdzHGCoeXN9sOt1fH73Bs/view 
yt-dlp -f 18 https://drive.google.com/file/d/1uIClejPITEXS1xw0yhIr7H6LP98Kx0-J/view 
yt-dlp -f 18 https://drive.google.com/file/d/1JT05GKHzHBWI92riKARtlvrmFIrdEsyH/view 
yt-dlp -f 18 https://drive.google.com/file/d/1DESySARvl79jhjsndhhjza-djRIot2sv/view 
yt-dlp -f 18 https://drive.google.com/file/d/15gJN2-W3yjJpXFU1Sjd4o7_HOyjAdNUB/view 
yt-dlp -f 18 https://drive.google.com/file/d/1vvTOSdzM0r8grbCQjThGZwjqqDKOJul5/view 
